import pptxgen from "pptxgenjs";
import { PitchDeck } from "../types";

export function exportToPPTX(deck: PitchDeck, options?: { removeWatermark?: boolean }) {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_16x9";

  deck.slides.forEach((slide) => {
    const s = pptx.addSlide();
    
    // Sleek dark slate background for premium look
    s.background = { color: "0F172A" };

    // Slide Title
    s.addText(slide.title, {
      x: 0.8,
      y: 0.6,
      w: 8.4,
      h: 0.8,
      fontSize: 26,
      bold: true,
      color: "38BDF8", // Cyan-400 accent of Slate
      fontFace: "Arial",
    });

    // Optional subtitle
    if (slide.subtitle) {
      s.addText(slide.subtitle, {
        x: 0.8,
        y: 1.3,
        w: 8.4,
        h: 0.4,
        fontSize: 15,
        italic: true,
        color: "94A3B8", // Slate-400
        fontFace: "Arial",
      });
    }

    // Slide Content as bullets
    const yStart = slide.subtitle ? 1.8 : 1.5;
    const bullets = slide.content.map(bullet => ({
      text: "  " + bullet,
      options: { bullet: true, color: "F8FAFC", fontSize: 16 }
    }));
    
    if (bullets.length > 0) {
      // @ts-ignore
      s.addText(bullets, {
        x: 0.8,
        y: yStart,
        w: 8.4,
        h: 4.0,
        fontFace: "Arial",
        lineSpacing: 26,
      });
    }

    // Waterproof watermark if not premium
    if (!options?.removeWatermark) {
      s.addText("Generated by Pitch Deck AI • pitch-ai.io", {
        x: 0.8,
        y: 6.8,
        w: 5.0,
        h: 0.3,
        fontSize: 10,
        color: "475569", // Dark slate grey watermark
        fontFace: "Arial"
      });
    } else {
      s.addText(deck.title, {
        x: 0.8,
        y: 6.8,
        w: 5.0,
        h: 0.3,
        fontSize: 10,
        color: "64748B", // Clean white-slate startup label
        fontFace: "Arial"
      });
    }
  });

  pptx.writeFile({ fileName: `${deck.title.replace(/[^a-zA-Z0-9А-Яа-я]/g, "_")}_Pitch_Deck.pptx` });
}
