ALTER TABLE "User"
ADD COLUMN "planStartedAt" TIMESTAMP(3),
ADD COLUMN "planExpiresAt" TIMESTAMP(3),
ADD COLUMN "monthlyDeckCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "monthlyDeckResetAt" TIMESTAMP(3),
ADD COLUMN "tokenVersion" INTEGER NOT NULL DEFAULT 0;
